
version: "2"



services:
  grenouillebot:
    image: grenouillebot
    container_name: "grenouillebot"
    build:
      context: ..
      dockerfile: docker/grenouillebot/Dockerfile
    entrypoint: python3 /grenouillebot/bot/bot_application.py
    environment:
        WEBSERVER_PORT: 8083
    ports:
      - "8083:8083"
    network_mode: "host"

